---
apiVersion: v2
description: A Helm chart for Openstack Neutron
name: neutron
version: 0.3.0
appVersion: "yoga"
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.14.2
  - condition: pxc_db.enabled
    name: pxc-db
    alias: pxc_db
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.3.0
  - name: memcached
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.5.3
  - condition: mariadb.enabled
    name: mysql_metrics
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.4.2
  - name: rabbitmq
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.11.1
  - name: utils
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.22.1
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
  - name: redis
    alias: api-ratelimit-redis
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.5.3
    condition: rate_limit.enabled
  - name: linkerd-support
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
