{{- $cdomains := .Values.global.domain_seeds.customer_domains | required "missing value for .Values.global.domain_seeds.customer_domains" -}}

apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: "{{ .Release.Name }}-seed"
  labels:
    component: designate
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  requires:
  {{- if .Values.global_setup }}
  - {{ .Release.Namespace }}/domain-global-seed
  {{- end }}
  {{- if .Values.tempest_enabled }}
  - {{ .Release.Namespace }}/domain-tempest-seed
  {{- end }}
  - {{ .Release.Namespace }}/domain-default-seed
  - {{ .Release.Namespace }}/domain-cc3test-seed
  - {{ .Release.Namespace }}/domain-ccadmin-seed
  {{- range $cdomains}}
  {{- if not (contains "iaas-" .)}}
  - {{ $.Release.Namespace }}/domain-{{replace "_" "-" . | lower}}-seed
  {{- end }}
  {{- end }}

  roles:
  - name: cloud_dns_admin
    description: "All Designate permissions"
  - name: cloud_dns_ops
    description: "DNS Operations. Create zones and any recordsets, share zones"
  - name: cloud_dns_support
    description: "DNS Support. Combines all dns_master permissions"
  - name: cloud_dns_viewer
    description: "Designate Read-only across all projects. View DNS zones and recordsets"
  - name: dns_zonemaster
    description: "Manage/create sub-zones for already owned zones, accept/create zone transfers, delete and share zones"
  - name: dns_hostmaster
    description: "Manage A/AAAA/CAA/CNAME/SRV/TXT/NS/PTR recordsets, accept/create zone transfers, delete zones"
  - name: dns_mailmaster
    description: "Manage A/AAAA/CAA/CNAME/SRV/TXT/MX/PTR recordsets, accept/create zone transfers, delete zones"
  - name: dns_webmaster
    description: "Manage A/AAAA/CAA/CNAME/SRV/TXT/PTR recordsets, accept/create zone transfers, delete zones"
  - name: dns_admin
    description: "Equal to dns_webmaster"
  - name: dns_viewer
    description: "Designate Read-only. View DNS zones and recordsets"

  services:
  - name: designate
    type: dns
    description: Openstack DNS
    endpoints:
    - interface: public
      region: {{ .Values.global.region }}
{{- if .Values.global.designate_public_api }}
      url: https://{{ .Values.global.designate_public_api }}
{{- else }}
      url: https://dns-3.{{.Values.global.region}}.{{.Values.global.tld}}
{{- end }}
    - interface: internal
      region: {{ .Values.global.region }}
{{- if .Values.global_setup }}
      url: http://{{ .Values.global.designate_internal_ip }}:9001
{{- else }}
      url: http://{{ .Release.Name }}-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:9001
{{- end }}
    - interface: admin
      region: {{ .Values.global.region }}
{{- if .Values.global_setup }}
      url: http://{{ .Values.global.designate_admin_ip }}:9001
{{- else }}
      url: http://{{ .Release.Name }}-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:9001
{{- end }}

  domains:
  - name: Default
    groups:
    - name: administrators
      role_assignments:
      - domain: Default
        role: cloud_dns_admin
      - domain: Default
        role: cloud_dns_admin
        inherited: true
      - project: admin
        role: cloud_dns_admin
    users:
    - name: admin
      role_assignments:
      - domain: Default
        role: cloud_dns_admin
      - domain: Default
        role: cloud_dns_admin
        inherited: true
      - project: admin
        role: cloud_dns_admin
    #- name: designate
    #  description: Designate Service User
    #  password: {{ .Values.global.designate_service_password }}
    #  role_assignments:
    #  - project: service
    #    role: service

  - name: ccadmin
    projects:
    - name: cloud_admin
      role_assignments:
      - user: admin@Default
        role: cloud_dns_admin
    - name: master
      role_assignments:
      - user: admin@Default
        role: cloud_dns_admin
      - user: core_dns_registry@Default
        role: cloud_dns_viewer
      - user: designate@Default
        role: cloud_dns_admin
      - user: TEST_D021500_TA@cc3test
        role: dns_viewer
      dns_quota:
        api_export_size: 10000
        recordset_records: 10000
        zone_records: 10000
        zone_recordsets: 10000
        zones: 1000
      #dns_tsigkeys:
      #- name: '{{ .Values.tsig_key_name }}'
      #  algorithm: hmac-sha256
      #  secret: '{{ .Values.tsig_key }}'
      #  scope: POOL
      #  resource_id: '{{ .Values.pool_id }}'
    groups:
    - name: CCADMIN_CLOUD_ADMINS
      role_assignments:
      - project: cloud_admin
        role: cloud_dns_admin
      - project: master
        role: cloud_dns_admin
    - name: CCADMIN_API_SUPPORT
      role_assignments:
      - project: master
        role: cloud_dns_admin
      - domain: ccadmin
        role: cloud_dns_admin
        inherited: true
    - name: CCADMIN_COMPUTE_SUPPORT
      role_assignments:
      - project: master
        role: cloud_dns_ops
      - domain: ccadmin
        role: cloud_dns_ops
        inherited: true
    - name: CCADMIN_NETWORK_SUPPORT
      role_assignments:
      - project: master
        role: cloud_dns_ops
      - domain: ccadmin
        role: cloud_dns_ops
        inherited: true
    - name: CCADMIN_STORAGE_SUPPORT
      role_assignments:
      - project: master
        role: cloud_dns_ops
      - domain: ccadmin
        role: cloud_dns_ops
        inherited: true
    - name: CCADMIN_SERVICE_DESK
      role_assignments:
      - project: master
        role: cloud_dns_ops
      - domain: ccadmin
        role: cloud_dns_ops
        inherited: true
    - name: CCADMIN_MONITORING_USERS
      role_assignments:
      - project: master
        role: dns_webmaster
    - name: CCADMIN_CLOUD_DNS_ADMINS
      role_assignments:
      - project: master
        role: cloud_dns_admin
    - name: CCADMIN_DOMAIN_DNS_SUPPORT
      role_assignments:
      - domain: ccadmin
        role: cloud_dns_support
        inherited: true
    - name: CCADMIN_DOMAIN_DNS_OPS
      role_assignments:
      - domain: ccadmin
        role: cloud_dns_ops
        inherited: true
      - domain: ccadmin
        role: role_viewer
        inherited: true
      - domain: ccadmin
        role: audit_viewer
        inherited: true
    role_assignments:
    - user: admin@Default
      role: cloud_dns_admin
      inherited: true

  - name: cc3test
    groups:
    - name: CC3TEST_DOMAIN_DNS_SUPPORT
      role_assignments:
      - domain: cc3test
        role: cloud_dns_support
        inherited: true
    - name: CC3TEST_DOMAIN_DNS_OPS
      role_assignments:
      - domain: cc3test
        role: cloud_dns_ops
        inherited: true
      - domain: cc3test
        role: role_viewer
        inherited: true
      - domain: cc3test
        role: audit_viewer
        inherited: true
    role_assignments:
    - user: admin@Default
      role: cloud_dns_admin
      inherited: true

  {{- range $cdomains }}
  {{- if and (not (contains "iaas-" .)) (not $.Values.global_setup)}}
  - name: {{ . }}
    groups:
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_DOMAIN_DNS_SUPPORT
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_support
            inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_DOMAIN_DNS_OPS
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_ops
            inherited: true
          - domain: {{ . | lower }}
            role: role_viewer
            inherited: true
          - domain: {{ . | lower }}
            role: audit_viewer
            inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_API_SUPPORT
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_admin
            inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_COMPUTE_SUPPORT
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_ops
            inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_NETWORK_SUPPORT
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_ops
            inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_STORAGE_SUPPORT
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_ops
            inherited: true
      - name: {{ contains "iaas-" . | ternary . ( upper . ) }}_SERVICE_DESK
        role_assignments:
          - domain: {{ . | lower }}
            role: cloud_dns_ops
            inherited: true
    role_assignments:
      - user: admin@Default
        role: cloud_dns_admin
        inherited: true
  {{- end }}
  {{- end }}

{{- if .Values.tempest_enabled }}
  - name: tempest
    dns_quota:
      api_export_size: 2000
      recordset_records: 2000
      zone_records: 10000
      zone_recordsets: 10000
      zones: 1000
    projects:
    - name: tempest1
      role_assignments:
        - user: admin@Default
          role: cloud_dns_admin
      dns_quota:
        api_export_size: 2000
        recordset_records: 2000
        zone_records: 2000
        zone_recordsets: 2000
        zones: 200
    - name: tempest2
      role_assignments:
        - user: admin@Default
          role: cloud_dns_admin
      dns_quota:
        api_export_size: 2000
        recordset_records: 2000
        zone_records: 2000
        zone_recordsets: 2000
        zones: 200
    users:
    - name: tempestuser1
      role_assignments:
      - project: tempest1
        role: cloud_dns_ops
      - domain: tempest
        role: cloud_dns_ops
    - name: tempestuser2
      role_assignments:
      - project: tempest2
        role: cloud_dns_ops
      - domain: tempest
        role: cloud_dns_ops
{{- end }}

{{- if .Values.global_setup }}
  - name: global
    groups:
    - name: GLOBAL_DOMAIN_DNS_SUPPORT
      role_assignments:
      - domain: global
        role: cloud_dns_support
        inherited: true
    - name: GLOBAL_DOMAIN_DNS_OPS
      role_assignments:
      - domain: global
        role: cloud_dns_ops
        inherited: true
      - domain: global
        role: role_viewer
        inherited: true
      - domain: global
        role: audit_viewer
        inherited: true
    - name: GLOBAL_API_SUPPORT
      role_assignments:
      - domain: global
        role: cloud_dns_admin
        inherited: true
    role_assignments:
    - user: admin@Default
      role: cloud_dns_admin
      inherited: true
{{- end }}

{{- if .Values.nanny_enabled }}
---
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: {{ .Release.Name }}-nanny-seed
spec:
  requires:
  - {{ .Release.Namespace }}/domain-default-seed
  - {{ .Release.Namespace }}/domain-ccadmin-seed
{{- if .Values.global_setup }}
  - {{ .Release.Namespace }}/designate-global-seed
  - {{ .Release.Namespace }}/domain-global-seed
{{- else}}
  - {{ .Release.Namespace }}/designate-seed
{{- end }}

  domains:
  - name: '{{ required "missing user domain in .Values.designate_nanny.credentials.designate_api.project_user_domain_name" .Values.designate_nanny.credentials.designate_api.project_user_domain_name }}'
    users:
    - name: '{{ required "missing username in .Values.designate_nanny.credentials.designate_api.user" .Values.designate_nanny.credentials.designate_api.user | include "resolve_secret" }}'
      description: Designate Nanny
      password: '{{ required "missing password in .Values.designate_nanny.credentials.designate_api.password" .Values.designate_nanny.credentials.designate_api.password | include "resolve_secret" }}'
  - name: '{{ required "missing project domain name in .Values.designate_nanny.credentials.designate_api.project_domain_name" .Values.designate_nanny.credentials.designate_api.project_domain_name }}'
    projects:
    - name: '{{ required "missing project name in .Values.designate_nanny.credentials.designate_api.project_name" .Values.designate_nanny.credentials.designate_api.project_name }}'
      role_assignments:
      - user: '{{ .Values.designate_nanny.credentials.designate_api.user | include "resolve_secret" }}@{{.Values.designate_nanny.credentials.designate_api.project_user_domain_name }}'
        role: cloud_dns_viewer
    - name: master
      role_assignments:
      - user: '{{ .Values.designate_nanny.credentials.designate_api.user | include "resolve_secret" }}@{{.Values.designate_nanny.credentials.designate_api.project_user_domain_name }}'
        role: objectstore_admin

{{- end }}
