---
apiVersion: v2
appVersion: dalmatian
description: A Helm chart Openstack Glance
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Glance/OpenStack_Project_Glance_vertical.png
name: glance
version: 0.7.0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.15.3
  - condition: pxc_db.enabled
    name: pxc-db
    alias: pxc_db
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.3.0
  - name: memcached
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.6.3
  - condition: mariadb.enabled
    name: mysql_metrics
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.4.2
  - name: utils
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.22.1
  - name: redis
    alias: sapcc_rate_limit
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.6.2
    condition: sapcc_rate_limit.enabled
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
  - name: linkerd-support
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
