{{- if .Values.nanny.enabled }}
{{- if or .Values.nanny.db_purge.enabled .Values.nanny.quota_sync.enabled }}
kind: CronJob
apiVersion: batch/v1
metadata:
  name: cinder-nanny-cronjob
  namespace: monsoon3
  labels:
    system: openstack
    service: cinder-nanny

spec:
  schedule: "{{ .Values.nanny.crontab_schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      annotations:
        {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
        linkerd.io/inject: enabled
        {{- end }}
      labels:
        component: cinder-nanny
    spec:
      template:
        metadata:
          annotations:
          labels:
            component: cinder-nanny
        spec:
          nodeSelector:
            zone: farm
          restartPolicy: OnFailure
          volumes:
          - name: cinder-etc
            projected:
              defaultMode: 420
              sources:
              - configMap:
                  name: cinder-etc
              - secret:
                  items:
                  - key: secrets.conf
                    path: cinder.conf.d/secrets.conf
                  name: cinder-secrets
          containers:
    {{- if .Values.nanny.db_purge.enabled }}
            - name: db-consistency-and-purge
              image: {{required ".Values.global.registry is missing" .Values.global.registry}}/loci-cinder:{{required ".Values.imageVersion is missing" .Values.imageVersion}}
              imagePullPolicy: IfNotPresent
              command:
                - dumb-init
                - kubernetes-entrypoint
              env:
                - name: COMMAND
                  value: "{{ if not .Values.nanny.debug }}/bin/bash /var/lib/openstack/scripts/cinder-db-consistency-and-purge.sh{{ else }}sleep inf{{ end }}"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: DEPENDENCY_SERVICE
                  value: "cinder-mariadb,cinder-api"
                - name: CINDER_DB_PURGE_ENABLED
                  value: {{ .Values.nanny.db_purge.enabled | quote }}
                - name: CINDER_DB_PURGE_OLDER_THAN
                  value: {{ .Values.nanny.db_purge.older_than | quote }}
                - name: CINDER_CONSISTENCY_ENABLED
                  value: {{ .Values.nanny.consistency.enabled | quote }}
                - name: CINDER_CONSISTENCY_DRY_RUN
                  value: {{ .Values.nanny.consistency.dry_run | quote }}
                - name: CINDER_CONSISTENCY_FIX_LIMIT
                  value: {{ .Values.nanny.consistency.fix_limit | quote }}
                - name: OS_AUTH_URL
                  value: "https://{{ include "keystone_api_endpoint_host_public" . }}:443/v3"
                - name: OS_PROJECT_NAME
                  value: "cloud_admin"
                - name: OS_PROJECT_DOMAIN_NAME
                  value: "ccadmin"
                - name: OS_USERNAME
                  value: "nova_nanny"
                - name: OS_USER_DOMAIN_NAME
                  value: "Default"
                - name: OS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cinder-nanny-cronjob-secret
                      key:  cinder_nanny_os_password
              volumeMounts:
                - mountPath: /cinder-etc
                  name: cinder-etc
              resources:
                requests:
                  memory: "500Mi"
                  cpu: "25m"
                limits:
                  memory: "500Mi"
                  cpu: "100m"
    {{- end }}
    {{- if .Values.nanny.quota_sync.enabled }}
            - name: quota-sync
              image: {{required ".Values.global.registry is missing" .Values.global.registry}}/loci-cinder:{{required ".Values.imageVersion is missing" .Values.imageVersion}}
              imagePullPolicy: IfNotPresent
              command:
                - dumb-init
                - kubernetes-entrypoint
              env:
                - name: COMMAND
                  value: "{{ if not .Values.nanny.debug }}/bin/bash /var/lib/openstack/scripts/cinder-quota-sync.sh{{ else }}sleep inf{{ end }}"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: DEPENDENCY_SERVICE
                  value: "cinder-mariadb,cinder-api"
                - name: CINDER_QUOTA_SYNC_ENABLED
                  value: {{ .Values.nanny.quota_sync.enabled | quote }}
                - name: CINDER_QUOTA_SYNC_DRY_RUN
                  value: {{ .Values.nanny.quota_sync.dry_run | quote }}
                - name: CINDER_NANNY_INTERVAL
                  value: {{ .Values.nanny.interval | quote }}
              volumeMounts:
                - mountPath: /cinder-etc
                  name: cinder-etc
              resources:
                requests:
                  memory: "250Mi"
                  cpu: "100m"
                limits:
                  memory: "250Mi"
                  cpu: "1000m"
    {{- end }}
    {{- end }}
    {{- end }}